### ISSUE TITLE
Request to include flag "Is Final" in output files for particles

### ISSUE THREAD

**Issue by gamejad** [smash-transport/smash-analysis#25]
Hi!
While work with output-file (.root), generated with config option "Only_Final: No", it seems that it is impossible to distinguish final particles and not-final in this case. This situation could be fixed if there was some flag in output files that can separate final and intermedium particles, something like "Is Final". Is it possible to add this feature in the future SMASH release?

**Comment by akschaefer** [comment]
Dear gamejad,
thank you for creating this issue. Unfortunately we cannot add a flag like the one you requested, since we have no information if a particles ends up being a final state particle or not at the time when it is written to the output.

What you can do however, in order to obtain this information, is to look at the collisions output. The collisions output contains the full history of the event, including all scatterings and decay. In combination with the particles output, the collisions output allows you to identify the origin of each particle and all of its interactions. By tracing back the history of each particle, you can find the last interaction of this particular particle and thereby determine if it was a final or intermediate particle at a specific time in the evolution.

**Comment by gamejad** [comment]
@akschaefer Thank you for answer
